// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobufs/order.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreatinoResponseStatus int32

const (
	OrderCreatinoResponseStatus_SUCCESFULL OrderCreatinoResponseStatus = 0
	OrderCreatinoResponseStatus_FAILED     OrderCreatinoResponseStatus = 1
)

// Enum value maps for OrderCreatinoResponseStatus.
var (
	OrderCreatinoResponseStatus_name = map[int32]string{
		0: "SUCCESFULL",
		1: "FAILED",
	}
	OrderCreatinoResponseStatus_value = map[string]int32{
		"SUCCESFULL": 0,
		"FAILED":     1,
	}
)

func (x OrderCreatinoResponseStatus) Enum() *OrderCreatinoResponseStatus {
	p := new(OrderCreatinoResponseStatus)
	*p = x
	return p
}

func (x OrderCreatinoResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCreatinoResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufs_order_proto_enumTypes[0].Descriptor()
}

func (OrderCreatinoResponseStatus) Type() protoreflect.EnumType {
	return &file_protobufs_order_proto_enumTypes[0]
}

func (x OrderCreatinoResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCreatinoResponseStatus.Descriptor instead.
func (OrderCreatinoResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobufs_order_proto_rawDescGZIP(), []int{0}
}

type OrderCreationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName string  `protobuf:"bytes,2,opt,name=familyName,proto3" json:"familyName,omitempty"`
	Birth      int32   `protobuf:"varint,3,opt,name=birth,proto3" json:"birth,omitempty"`
	CustomId   string  `protobuf:"bytes,4,opt,name=customId,proto3" json:"customId,omitempty"`
	UnitPrice  float64 `protobuf:"fixed64,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Amount     int32   `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Credit     float64 `protobuf:"fixed64,7,opt,name=credit,proto3" json:"credit,omitempty"`
	Distance   int32   `protobuf:"varint,8,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *OrderCreationRequest) Reset() {
	*x = OrderCreationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreationRequest) ProtoMessage() {}

func (x *OrderCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreationRequest.ProtoReflect.Descriptor instead.
func (*OrderCreationRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderCreationRequest) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *OrderCreationRequest) GetBirth() int32 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *OrderCreationRequest) GetCustomId() string {
	if x != nil {
		return x.CustomId
	}
	return ""
}

func (x *OrderCreationRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderCreationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderCreationRequest) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *OrderCreationRequest) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type OrderCreatinoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   OrderCreatinoResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=OrderCreatinoResponseStatus" json:"status,omitempty"`
	ErrorMsg *string                     `protobuf:"bytes,2,opt,name=errorMsg,proto3,oneof" json:"errorMsg,omitempty"`
}

func (x *OrderCreatinoResponse) Reset() {
	*x = OrderCreatinoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreatinoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatinoResponse) ProtoMessage() {}

func (x *OrderCreatinoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatinoResponse.ProtoReflect.Descriptor instead.
func (*OrderCreatinoResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatinoResponse) GetStatus() OrderCreatinoResponseStatus {
	if x != nil {
		return x.Status
	}
	return OrderCreatinoResponseStatus_SUCCESFULL
}

func (x *OrderCreatinoResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

var File_protobufs_order_proto protoreflect.FileDescriptor

var file_protobufs_order_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x7b, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x88, 0x01, 0x01,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x2a, 0x39, 0x0a,
	0x1b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x32, 0x42, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x39, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4e, 0x5a, 0x4c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x65, 0x77, 0x6f,
	0x6f, 0x62, 0x69, 0x6e, 0x37, 0x38, 0x39, 0x2f, 0x70, 0x6f, 0x63, 0x2d, 0x63, 0x69, 0x6c, 0x69,
	0x75, 0x6d, 0x2d, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_order_proto_rawDescOnce sync.Once
	file_protobufs_order_proto_rawDescData = file_protobufs_order_proto_rawDesc
)

func file_protobufs_order_proto_rawDescGZIP() []byte {
	file_protobufs_order_proto_rawDescOnce.Do(func() {
		file_protobufs_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_order_proto_rawDescData)
	})
	return file_protobufs_order_proto_rawDescData
}

var file_protobufs_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobufs_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_order_proto_goTypes = []interface{}{
	(OrderCreatinoResponseStatus)(0), // 0: OrderCreatinoResponseStatus
	(*OrderCreationRequest)(nil),     // 1: OrderCreationRequest
	(*OrderCreatinoResponse)(nil),    // 2: OrderCreatinoResponse
}
var file_protobufs_order_proto_depIdxs = []int32{
	0, // 0: OrderCreatinoResponse.status:type_name -> OrderCreatinoResponseStatus
	1, // 1: Order.Create:input_type -> OrderCreationRequest
	2, // 2: Order.Create:output_type -> OrderCreatinoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_order_proto_init() }
func file_protobufs_order_proto_init() {
	if File_protobufs_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreatinoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobufs_order_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_order_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_order_proto_goTypes,
		DependencyIndexes: file_protobufs_order_proto_depIdxs,
		EnumInfos:         file_protobufs_order_proto_enumTypes,
		MessageInfos:      file_protobufs_order_proto_msgTypes,
	}.Build()
	File_protobufs_order_proto = out.File
	file_protobufs_order_proto_rawDesc = nil
	file_protobufs_order_proto_goTypes = nil
	file_protobufs_order_proto_depIdxs = nil
}
