---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.1.0/24
nodes:
  - image: kindest/node:v1.24.7 # due to confluent helm chart that contains deprecated version of PodDistruptionBudget
    role: control-plane
  - image: kindest/node:v1.24.7
    role: worker
  - image: kindest/node:v1.24.7
    role: worker